controller_manager:
  ros__parameters:
    update_rate: 60
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gripper_action_controller:
      type: position_controllers/GripperActionController

arm_trajectory_controller:
  ros__parameters:
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
    interface_name: position
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity

gripper_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: true
    goal_tolerance: 0.01
    joint: 'grasping_frame_joint'
    max_effort: 100.0
    stall_timeout: 3.0
    stall_velocity_treshold: 0.001