controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - grasping_frame_joint
  - name: fake_body_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_wheel
      - front_right_wheel
      - rear_left_wheel
      - rear_right_wheel
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: pick_object
  - group: gripper_group
    pose: gripper_opened