trajectory_execution:
  allowed_execution_duration_scaling: 1.5
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

  trajectory_duration_monitoring: true

  execution_duration_monitoring: true

  trajectory_execution_tolerance:
    goal_time: 5.0  # seconds
    stopped_velocity_tolerance: 0.01  # rad/s
    path_tolerance: 0.1  # per-joint, usually unused
